apiVersion: v1
kind: Service
metadata:
  name: streaming-feature-platform
  labels:
    app: streaming-feature-platform
spec:
  selector:
    app: streaming-feature-platform
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP
